version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: linux_small
      env:
        compute-type: BUILD_GENERAL1_SMALL
      ignore-failure: false
    - identifier: linux_medium
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          BUILD_MEDIUM: 2
      ignore-failure: false
    - identifier: linux_large
      env:
        compute-type: BUILD_GENERAL1_LARGE
      ignore-failure: false


phases:
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo 'Compiling the Java Code'
      - echo 'Test'
      - javac -cp . HelloWorld.java
      - if [ $CODEBUILD_BUILD_NUMBER -gt 5 ]; then fail; fi
  post_build:
    commands:
      - echo "Would deploy here"
artifacts:
  files:
  - 'HelloWorld.class'
